/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include "easy_profiler"

#define PLUGIN "Test easyprofiler"
#define VERSION "1.0"
#define AUTHOR "Inline"

public plugin_init() {
	register_plugin(PLUGIN, VERSION, AUTHOR);
	ep_calibrate();
	ep_start();
	ep_sleep(10.0);
	ep_end(1, "Time is %.17f");
}
